### ISSUE TITLE
Which quota to increase when model exceeds max size?

### ISSUE THREAD

**Issue by pbilling** [googlegenomics/cloudml-examples#5]
I received a size error when trying to do batch predict. 

```
ERROR: (gcloud.ml-engine.jobs.submit.prediction) FAILED_PRECONDITION: Field: uri Error: The total size of files in gs://gbsc-gcp-project-mvp-cloudml/models/1000-genomes-super-population/export/Servo/1495692639 is 440979953 bytes, which exceeds the allowed maximum of 262144000 bytes
```

The end of the README advises users to "request more quota for your project", if you run into this kind of issue. However, it's unclear to me which quota(s) to increase. All the Machine Learning Engine quotas listed under IAM seem to refer to requests per 100 seconds, whereas this error refers to a max size. 

Which quota(s) should I increase?

Thanks!
Paul

**Comment by deflaux** [comment]
Good question!

In general this is a good resource https://cloud.google.com/ml-engine/quotas but for this particular quota see https://stackoverflow.com/questions/42369041/field-version-deployment-uri-error-the-total-size-of-files-in-gs-my-bucket-m

**Comment by pbilling** [comment]
Great, thanks Nicole!

I've requested a quota increase from cloudml-feedback@google.com.
